name: CI

on: 
  push: 
    branches: [ master ] 
  pull_request: 
    branches: [ master ] 
jobs: 
  build: 
    runs-on: ubuntu-latest 
 
    steps: 
    - name: Checkout code 
      uses: actions/checkout@v3 
 
    - name: Set up JDK 11 
      uses: actions/setup-java@v3 
      with:  
        distribution: 'adopt' 
        java-version: '11' 
 
    - name: Build with Maven 
      run: mvn clean install
 
    - name: Upload Build Artifacts 
      uses: actions/upload-artifact@v3 
      with: 
        name: build-artifacts 
        path: build/libs/**
 
    - name: Run Unit Tests 
      run: gradle test 
 
    - name: Upload Test Reports 
      uses: actions/upload-artifact@v3 
      with: 
        name: test-reports 
        path: build/reports/tests/**

    - name: Generate Code Coverage Report 
      run: mvn jacoco:report 
 
    - name: Upload Code Coverage Report 
      uses: actions/upload-artifact@v3 
      with: 
        name: code-coverage-report 
        path: build/reports/jacoco/test/html/**